/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AlertDirection = "at_or_above" | "at_or_below";

export type ForecastDirection = "bearish" | "bullish" | "neutral";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface ExchangeRates {
  fetchedAt: Generated<Timestamp>;
  id: Generated<number>;
  rate: Numeric;
}

export interface FxForecasts {
  confidencePct: number;
  createdAt: Generated<Timestamp>;
  currentRateAtForecast: Numeric;
  direction: ForecastDirection;
  expiresAt: Timestamp;
  id: Generated<number>;
  keyEvents: Json;
  ratePath: Json;
  summary: string;
  targetRangeHigh: Numeric;
  targetRangeLow: Numeric;
}

export interface LoginAttempts {
  attemptedAt: Timestamp | null;
  email: string;
  id: Generated<number>;
  success: Generated<boolean>;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  provider: string;
  providerEmail: string | null;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: Generated<string>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface RateAlerts {
  createdAt: Generated<Timestamp>;
  direction: Generated<AlertDirection>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  targetRate: Numeric;
  triggeredAt: Timestamp | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  passwordHash: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  displayName: Generated<string>;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  exchangeRates: ExchangeRates;
  fxForecasts: FxForecasts;
  loginAttempts: LoginAttempts;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  rateAlerts: RateAlerts;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const AlertDirectionArrayValues: [AlertDirection, ...AlertDirection[]] = ["at_or_above","at_or_below"];
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const ForecastDirectionArrayValues: [ForecastDirection, ...ForecastDirection[]] = ["bearish","bullish","neutral"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.